-- Provenance per reading, so a lender can tell measurement from model.
--
-- Additive only: every column is nullable or defaulted, so existing rows,
-- views and queries keep working unchanged. Simulated data remains the
-- default, and real readings have to opt in.

create type public.reading_origin as enum ('simulated', 'satellite');

alter table public.mock_readings
  add column if not exists origin public.reading_origin not null default 'simulated',
  -- Satellite platform and index, e.g. 'Sentinel-2' / 'NDVI'. Null when simulated.
  add column if not exists source_platform text,
  add column if not exists source_product  text,
  -- The date the satellite actually observed the parcel. Distinct from
  -- recorded_at, which is when the row landed in our database.
  add column if not exists observed_on date;

comment on column public.mock_readings.origin is
  'Whether this reading was measured by satellite or generated by the demo simulation.';
comment on column public.mock_readings.observed_on is
  'Satellite acquisition date. Imagery is not daily, so this lags "now" by days.';

create index if not exists mock_readings_origin_idx
  on public.mock_readings (farm_id, origin, metric_type, recorded_at desc);

-- One reading per zone/metric/observation date, so re-running the backfill is
-- safe and cannot duplicate history.
create unique index if not exists mock_readings_satellite_unique
  on public.mock_readings (zone_id, metric_type, source_platform, source_product, observed_on)
  where origin = 'satellite';
